spring:
  config:
    import: dev/druid.yml,dev/mybatis-plus.yml,dev/pageHelper.yml
server:
  port: 9090



devCloud:
  crossOrigin: localhost:5173,http://localhost:5173,http://127.0.0.1:5173,127.0.0.1:5173